# Generated by Django 5.2.7 on 2025-10-15 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('date_mise_en_service', models.DateField()),
                ('kilometrage_actuel', models.IntegerField(default=0)),
                ('carburant_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique')], max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('maintenance', 'En maintenance')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_embauche', models.DateField()),
                ('permis_numero', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vitesse', models.FloatField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_track.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('lieu_depart', models.CharField(max_length=200)),
                ('lieu_arrivee', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_track.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_track.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('autre', 'Autre')], max_length=50)),
                ('date_maintenance', models.DateField()),
                ('kilometrage', models.IntegerField()),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_track.vehicule')),
            ],
        ),
    ]
